version: "3"
services:
  db:
    image: "postgres:latest"
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./create.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=app
      - POSTGRES_PORT=5432
